### ISSUE TITLE
Use xi-editor for text editing?

### ISSUE THREAD

**Issue by luolong** [madeso/ride#118]
I know that you have chosen Scintilla based text editor for the text editor component, but there is pure Rust text editor engine called [xi-editor](https://github.com/google/xi-editor).

I wich you would take a look at it as possible alternative for Scintilla.

**Comment by madeso** [comment]
I've been toying around with replacing scintilla with a custom control as I've noticed performance problem when changing colors with several buffers open and I'm missing some features that I would like to have.

Xi seems to be lacking at the moment, but it sure would be nice if I don't have to write a editor component myself.

**Comment by luolong** [comment]
There is a [xi-mac](https://github.com/google/xi-mac) project...

**Comment by madeso** [comment]
To replace scintilla I would at least need:

* cross platform support. Xi seems has this in a somewhat working status, but in several projects so it seems somewhat chaotic at the moment.
* Syntax highlight (xi doesn't seem to support this currently)
* Collapsing code (xi doesn't seem to support this currently)
* Brace matching (xi doesn't seem to support this currently)
* A better autocompletion support. It's been a while but I couldn't get racer and scintilla autocomplete to work as I wanted. I haven't had the time to look into RLS but the auto complete should at least work as good as scintilla does. (xi doesn't seem to support this)

Continuing, in order to improve the current experience:

* Shared editor settings between buffers. Ride currently has a scintilla instance per buffer and that generates perfomance problems when changing colors for example. Perhaps this is solvable by sharing one scintilla instance as I want to support other editors aswell and attaching/detaching or hiding/unhiding the widget might cause some problems.
* In edit widgets. Some time in the future I would like to support widget like support for replacing part of a a bit of code with some gui widget that generates the underlying (complex) code. #199
* various visual studio debugging widgets also need to be supported
* similarly, lighter editor helpful drawing/renderings about the code like a thick colored line for colors, arrows for various rotations and bret victors loop debugging text. Not entirely sure how that would work in practice but I don't want the editor to stop me.

That being said, I haven't had the time to test xi yet, Ive just read the main readme and the roadmap.
